spring.liquibase.change-log: classpath:db-migration/master.xml

spring.quartz.job-store-type: jdbc
spring.quartz.jdbc.initialize-schema: NEVER

scheduler:
  cronTemplate: 0/2 * * * * ?
  quartz:
    org.quartz.scheduler:
      instanceName: notification-analytic-processor-quartz
      instanceId: AUTO

    org.quartz.threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 5
      threadsInheritContextClassLoaderOfInitializingThread: true

    org.quartz.jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      useProperties: false
      tablePrefix: QRTZ_
      isClustered: true
      clusterCheckinInterval: 20000
      misfireThreshold: 60000

    org.quartz.scheduler.skipUpdateCheck: true